### Citizen API Requests
### Kreiraj novog gradjanina
POST http://localhost:3000/mup/citizens
Content-Type: application/json

{
  "jmbg": "12345678904233",
  "firstName": "Pera",
  "lastName": "Peric",
  "email": "pera.peric@example.com",
  "phone": "+381601234567"
}

### Kreiraj drugog gradjanina
POST http://localhost:3000/mup/citizens
Content-Type: application/json

{
  "jmbg": "9876543210987",
  "firstName": "Ana",
  "lastName": "Anic",
  "email": "ana.anic@example.com",
  "phone": "+381609876543",
  "address": {
    "street": "Knez Mihailova",
    "number": "15",
    "city": "Beograd",
    "postalCode": "11000",
    "country": "Serbia",
    "validFrom": "2024-01-01T00:00:00.000Z"
  }
}

### Dobij sve gradjane
GET http://localhost:3000/mup/citizens

### Dobij gradjanina po ID
GET http://localhost:3000/mup/citizens/clh1234567890

### Dobij gradjanina po JMBG
GET http://localhost:3000/mup/citizens/jmbg/1234567890123

### Azuriraj gradjanina
PUT http://localhost:3000/mup/citizens/clh1234567890
Content-Type: application/json

{
  "jmbg": "1234567890133",
  "firstName": "Petar",
  "lastName": "Peric",
  "email": "petar.peric@example.com",
  "phone": "+381601234567",
  "address": {
    "street": "Knez Mihailova",
    "number": "15",
    "city": "Beograd",
    "postalCode": "11000",
    "country": "Serbia",
    "validFrom": "2024-01-01T00:00:00.000Z"
  }
}

### Obrisi gradjanina
DELETE http://localhost:3000/mup/citizens/clh1234567890

### Test - pokusaj kreiranja sa istim JMBG (treba da baci gresku)
POST http://localhost:3000/mup/citizens
Content-Type: application/json

{
  "jmbg": "1234567890123",
  "firstName": "Dusan",
  "lastName": "Dusanic",
  "email": "dusan.dusanic@example.com",
  "phone": "+381601111111"
}

### Test - pokusaj pristupa nepostojecim ID (treba da baci 404)
GET http://localhost:3000/mup/citizens/nonexistent-id
