POST http://localhost:3000/mup/request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWZyNnFrNTEwMDAwbXYzbXUzMmt2b3o5Iiwiam1iZyI6IjEyMzQ1Njc4OTAxMjMiLCJlbWFpbCI6Im1hcmtvLnBldHJvdmljQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU4MzE3Mzg3LCJleHAiOjE3NTg0MDM3ODd9.VDU5-4hQwzkssX9O_ZS3IIyOQ_qMvWe8PV2P-uYBUM8

{
  "caseNumber": "312321312",
  "type": "ID_CARD",
  "status": "CREATED",
  "submissionDate": "2024-01-01T00:00:00.000Z",
  "citizenId": "cmfr6y2rr0001mv3muqmwiird"
}

### Get all requests
GET http://localhost:3000/mup/request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWZyNnFrNTEwMDAwbXYzbXUzMmt2b3o5Iiwiam1iZyI6IjEyMzQ1Njc4OTAxMjMiLCJlbWFpbCI6Im1hcmtvLnBldHJvdmljQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU4MzA3NTg0LCJleHAiOjE3NTgzOTM5ODR9.tHsztK7272pxXElHHWe27jl1G_5DzuU-riAegSRVQgk

### Get all requests with filter
GET http://localhost:3000/mup/request/filter?citizenId=cmfr6y2rr0001mv3muqmwiird
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWZyZnhwNTEwMDAwcG4yd3lwcWg4bWM0Iiwiam1iZyI6IjI0MDg5OTk3NzIwNjEiLCJlbWFpbCI6Im1vbWlyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1ODM1NzAxMSwiZXhwIjoxNzU4NDQzNDExfQ.Q8dX7H53CeQo2x70d2fwBVefZmxTaEut6gE8AN_mojo

### Get all requests without filters (should return all)
GET http://localhost:3000/mup/request/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWZyZnhwNTEwMDAwcG4yd3lwcWg4bWM0Iiwiam1iZyI6IjI0MDg5OTk3NzIwNjEiLCJlbWFpbCI6Im1vbWlyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1ODM1NzAxMSwiZXhwIjoxNzU4NDQzNDExfQ.Q8dX7H53CeQo2x70d2fwBVefZmxTaEut6gE8AN_mojo

### Get requests with status filter
GET http://localhost:3000/mup/request/filter?requestStatus=IN_PROCESS
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWZyZnhwNTEwMDAwcG4yd3lwcWg4bWM0Iiwiam1iZyI6IjI0MDg5OTk3NzIwNjEiLCJlbWFpbCI6Im1vbWlyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1ODM1NzAxMSwiZXhwIjoxNzU4NDQzNDExfQ.Q8dX7H53CeQo2x70d2fwBVefZmxTaEut6gE8AN_mojo

### Get requests with type filter
GET http://localhost:3000/mup/request/filter?requestType=ID_CARD
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWZyZnhwNTEwMDAwcG4yd3lwcWg4bWM0Iiwiam1iZyI6IjI0MDg5OTk3NzIwNjEiLCJlbWFpbCI6Im1vbWlyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1ODM1NzAxMSwiZXhwIjoxNzU4NDQzNDExfQ.Q8dX7H53CeQo2x70d2fwBVefZmxTaEut6gE8AN_mojo


### Get request by ID
GET http://localhost:3000/mup/request/cmfpxfft10002s160203tl9e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWZyNnFrNTEwMDAwbXYzbXUzMmt2b3o5Iiwiam1iZyI6IjEyMzQ1Njc4OTAxMjMiLCJlbWFpbCI6Im1hcmtvLnBldHJvdmljQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU4MzA3NTg0LCJleHAiOjE3NTgzOTM5ODR9.tHsztK7272pxXElHHWe27jl1G_5DzuU-riAegSRVQgk

### Update request
PUT http://localhost:3000/mup/request/cmfpxfft10002s160203tl9e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWZwdzZ4cHgwMDAycm4zM3ByMndxYmRtIiwiam1iZyI6IjI0MDg5OTk3NzIwNjAiLCJlbWFpbCI6Im1vbWlyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1ODIzMDgxOSwiZXhwIjoxNzU4MzE3MjE5fQ.w6cct6y0stB0CUOsZ2THv_kpyIa8FnQwco1HVWYIr0c

{
  "caseNumber": "1234567890",
  "type": "ID_CARD",
  "status": "CREATED",
  "submissionDate": "2024-01-01T00:00:00.000Z",
  "citizenId": "cmfpw6xpx0002rn33pr2wqbdm"
}

### Delete request
DELETE http://localhost:3000/mup/request/cmfpxfft10002s160203tl9e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWZwdzZ4cHgwMDAycm4zM3ByMndxYmRtIiwiam1iZyI6IjI0MDg5OTk3NzIwNjAiLCJlbWFpbCI6Im1vbWlyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1ODIzMDgxOSwiZXhwIjoxNzU4MzE3MjE5fQ.w6cct6y0stB0CUOsZ2THv_kpyIa8FnQwco1HVWYIr0c